
package de.mbg.webservice.client.gen;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CalculatorServiceService", targetNamespace = "http://server.webservice.mbg.de/", wsdlLocation = "http://localhost:8090/calculator?wsdl")
public class CalculatorServiceService
    extends Service
{

    private static final URL CALCULATORSERVICESERVICE_WSDL_LOCATION;
    private static final WebServiceException CALCULATORSERVICESERVICE_EXCEPTION;
    private static final QName CALCULATORSERVICESERVICE_QNAME = new QName("http://server.webservice.mbg.de/", "CalculatorServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/calculator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATORSERVICESERVICE_WSDL_LOCATION = url;
        CALCULATORSERVICESERVICE_EXCEPTION = e;
    }

    public CalculatorServiceService() {
        super(__getWsdlLocation(), CALCULATORSERVICESERVICE_QNAME);
    }

    public CalculatorServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATORSERVICESERVICE_QNAME, features);
    }

    public CalculatorServiceService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATORSERVICESERVICE_QNAME);
    }

    public CalculatorServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATORSERVICESERVICE_QNAME, features);
    }

    public CalculatorServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculatorService
     */
    @WebEndpoint(name = "CalculatorServicePort")
    public CalculatorService getCalculatorServicePort() {
        return super.getPort(new QName("http://server.webservice.mbg.de/", "CalculatorServicePort"), CalculatorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorService
     */
    @WebEndpoint(name = "CalculatorServicePort")
    public CalculatorService getCalculatorServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservice.mbg.de/", "CalculatorServicePort"), CalculatorService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATORSERVICESERVICE_EXCEPTION!= null) {
            throw CALCULATORSERVICESERVICE_EXCEPTION;
        }
        return CALCULATORSERVICESERVICE_WSDL_LOCATION;
    }

}
